// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iZmAozS40H5yQzalPLBeXcQ7oqrG2gU',
    appId: '1:498286739341:web:62eaea283c3bca524707c4',
    messagingSenderId: '498286739341',
    projectId: 'my-library-2e883',
    authDomain: 'my-library-2e883.firebaseapp.com',
    storageBucket: 'my-library-2e883.appspot.com',
    measurementId: 'G-CVVVV4MTD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJ6rxnqbe5sPlRA8Q_yiZTuQ7n4e56D0',
    appId: '1:498286739341:android:906bef939547222d4707c4',
    messagingSenderId: '498286739341',
    projectId: 'my-library-2e883',
    storageBucket: 'my-library-2e883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARsY5_T5M5m7gkOYNDwS6hoO8aOjRTBmw',
    appId: '1:498286739341:ios:90f627f5da80a1f24707c4',
    messagingSenderId: '498286739341',
    projectId: 'my-library-2e883',
    storageBucket: 'my-library-2e883.appspot.com',
    iosBundleId: 'com.example.mylibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARsY5_T5M5m7gkOYNDwS6hoO8aOjRTBmw',
    appId: '1:498286739341:ios:6d41f32e1aa9a6674707c4',
    messagingSenderId: '498286739341',
    projectId: 'my-library-2e883',
    storageBucket: 'my-library-2e883.appspot.com',
    iosBundleId: 'com.example.mylibrary.RunnerTests',
  );
}
